
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class MenuUpdate extends javax.swing.JFrame {

    Connector connector = new Connector();
//    ViewTabel viewTabel;
    int tahunSekarang = Calendar.getInstance().get(Calendar.YEAR);
    /**
     * Creates new form ViewData
     */
    public MenuUpdate() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfFakultas = new javax.swing.JTextField();
        tfProdi = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfTahun = new javax.swing.JTextField();
        tfStatus = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        lNim = new javax.swing.JLabel();
        tfNim = new javax.swing.JTextField();
        lNama = new javax.swing.JLabel();
        lFakultas = new javax.swing.JLabel();
        lProdi = new javax.swing.JLabel();
        lEmail = new javax.swing.JLabel();
        lTahun = new javax.swing.JLabel();
        lStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Data Mahasiswa");

        jLabel2.setText("NIM");

        jLabel3.setText("Nama");

        jLabel4.setText("Fakultas");

        jLabel5.setText("Program Studi");

        jLabel6.setText("Email");

        jLabel7.setText("Tahun Masuk");

        jLabel8.setText("Status");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnTutup.setBackground(new java.awt.Color(255, 102, 102));
        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        lNama.setText(" ");

        lFakultas.setText(" ");

        lProdi.setText(" ");

        lEmail.setText(" ");

        lTahun.setText(" ");

        lStatus.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(btnTutup))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStatus)
                            .addComponent(tfEmail)
                            .addComponent(tfTahun)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus))
                            .addComponent(tfProdi)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFakultas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(tfNama))))
                .addGap(98, 98, 98))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lNama)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lProdi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lTahun)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lFakultas))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNama)
                    .addComponent(lFakultas)
                    .addComponent(lProdi)
                    .addComponent(lEmail)
                    .addComponent(lTahun)
                    .addComponent(lStatus))
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lNim)
                    .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfFakultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnHapus)
                    .addComponent(btnTutup))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void updateData(){
        try {
            // JIKA ADA TEXT FIELD YANG TIDAK TERISI
            if (getNim().trim().equals("") || getNama().trim().equals("") || getFakultas().trim().equals("") || getProdi().trim().equals("") || getEmail().trim().equals("") || getTahun() == null || getStatus().trim().equals("")){
                JOptionPane.showMessageDialog(null,"Lengkapi data terlebih dahulu.");
            }
            // JIKA SEMUA TEXT FIELD TERISI
            else{
                // JIKA TIDAK ADA PERUBAHAN ANTARA DATA LAMA DAN DATA BARU
                if (getNim().equals(getNimLama()) && getNama().equals(getNamaLama()) && getFakultas().equals(getFakultasLama()) && getProdi().equals(getProdiLama()) && getEmail().equals(getEmailLama()) && getTahun().equals(getTahunLama()) && getStatus().equals(getStatusLama())){
                    JOptionPane.showMessageDialog(null,"Tidak ada data yang berubah.");
                }
                else
                {
                    if (getNim().matches("[0-9]+") && getNim().length() == 9){ // JIKA NIM HANYA MENGANDUNG ANGKA DAN 9 DIGIT
                        if (getTahun() < 1959){ // JIKA USER MENGINPUTKAN TAHUN SEBELUM KAMPUS DIDIRIKAN
                            JOptionPane.showMessageDialog(null,"Kampus belum didirikan pada tahun tersebut.");
                        }
                        else if (getTahun() > tahunSekarang){ // JIKA USER MENGINPUTKAN TAHUN+1 SETELAH PMB TERAKHIR
                            JOptionPane.showMessageDialog(null,"Kampus belum mengadakan PMB setelah tahun " + tahunSekarang + ".");
                        }
                        else{ // JIKA SYARAT INPUT TAHUN TERPENUHI
                            String query = "SELECT * FROM datamhs WHERE NIM = '"+getNimLama()+"'";
                            connector.statement = connector.koneksi.createStatement();
                            ResultSet rs = connector.statement.executeQuery(query);
                            if(rs.next()){
                                String query2 = "UPDATE datamhs SET `nim` = '"+getNim()+"', `nama` = '"+getNama()+"', `fakultas` = '"+getFakultas()+"', `prodi` = '"+getProdi()+"', `email` = '"+getEmail()+"', `tahun_masuk` = '"+getTahun()+"', `status` = '"+getStatus()+"' WHERE `nim` = '"+getNimLama()+"'";
                                connector.statement = connector.koneksi.createStatement();
                                connector.statement.executeUpdate(query2);
                                JOptionPane.showMessageDialog(null,"Data berhasil diperbarui.\nTekan 'Tampilkan Data' untuk memperbarui tabel.");
                                setVisible(false);
                            }
                            else{
                                JOptionPane.showMessageDialog(null,"Data sudah tidak berada di database.");
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"NIM hanya boleh terdiri dari angka dan 9 digit.");
                    }
                }
            }  
        } catch (Exception ex){
            JOptionPane.showMessageDialog(null, "Input tahun harus berupa angka.");
        }
    }
    
    public void hapusData(){
        int peringatan = JOptionPane.showConfirmDialog (null, "Yakin ingin menghapus data?","WARNING", JOptionPane.YES_NO_OPTION);
        if (peringatan == JOptionPane.YES_OPTION) {
            try {
                // JIKA ADA TEXT FIELD YANG TIDAK TERISI
                if (getNama().trim().equals("") || getFakultas().trim().equals("") || getProdi().trim().equals("") || getEmail().trim().equals("") || getTahun() == null || getStatus().trim().equals("")){
                    JOptionPane.showMessageDialog(null,"Data kosong.");
                }
                // JIKA SEMUA TEXT FIELD TERISI
                else{
                    String query = "SELECT * FROM datamhs WHERE NIM = '"+getNim()+"'";
                    connector.statement = connector.koneksi.createStatement();
                    ResultSet rs = connector.statement.executeQuery(query);
                    if(rs.next()){
                        String query2 = "DELETE FROM datamhs WHERE nim = '"+getNim()+"'";
                        connector.statement = connector.koneksi.createStatement();
                        connector.statement.executeUpdate(query2);
                        JOptionPane.showMessageDialog(null,"Data berhasil dihapus.\nTekan 'Tampilkan Data' untuk memperbarui tabel.");
                        setVisible(false);
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Data sudah tidak berada di database.");
                    }
                }  
            } catch (Exception ex){
                JOptionPane.showMessageDialog(null,ex);
            }
        } else {
            // no option
        }
    }
    
    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUpdate().setVisible(true);
            }
        });
    }
    
    public String getNimLama(){
        return lNim.getText();
    }
    
    public String getNim(){
        return tfNim.getText();
    }
    
    public String getNamaLama(){
        return lNama.getText();
    }
    
    public String getNama(){
        return tfNama.getText();
    }
    
    public String getFakultasLama(){
        return lFakultas.getText();
    }
    
    public String getFakultas(){
        return tfFakultas.getText();
    }
    
    public String getProdiLama(){
        return lProdi.getText();
    }
    
    public String getProdi(){
        return tfProdi.getText();
    }
    
    public String getEmailLama(){
        return lEmail.getText();
    }
    
    public String getEmail(){
        return tfEmail.getText();
    }
    
    public Integer getTahunLama(){
        return Integer.parseInt(lTahun.getText());
    }
    
    public Integer getTahun(){
        return Integer.parseInt(tfTahun.getText());
    }
    
    public String getStatusLama(){
        return lStatus.getText();
    }
    
    public String getStatus(){
        return tfStatus.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel lEmail;
    public javax.swing.JLabel lFakultas;
    public javax.swing.JLabel lNama;
    public javax.swing.JLabel lNim;
    public javax.swing.JLabel lProdi;
    public javax.swing.JLabel lStatus;
    public javax.swing.JLabel lTahun;
    public javax.swing.JTextField tfEmail;
    public javax.swing.JTextField tfFakultas;
    public javax.swing.JTextField tfNama;
    public javax.swing.JTextField tfNim;
    public javax.swing.JTextField tfProdi;
    public javax.swing.JTextField tfStatus;
    public javax.swing.JTextField tfTahun;
    // End of variables declaration//GEN-END:variables
}
