
import javax.swing.*;
import java.awt.event.*;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class MenuTabel extends JFrame{

    Connector connector = new Connector();
    MenuInput viewInput = new MenuInput();
    MenuUpdate viewUpdate = new MenuUpdate();
    /**
     * Creates new form NewJFrame
     */
    public MenuTabel() {
        initComponents();
        setTitle("Data Mahasiswa");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        lJudul = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        btnTampil = new javax.swing.JButton();
        btnSembunyi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Fakultas", "Program Studi", "Email", "Tahun Masuk", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblData.getTableHeader().setReorderingAllowed(false);
        tblData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblData);

        lJudul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lJudul.setText("Data Mahasiswa UPN \"Veteran\" Yogyakarta");

        btnInput.setText("Input Data");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnTampil.setText("Tampilkan Data");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        btnSembunyi.setText("Sembunyikan Data");
        btnSembunyi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSembunyiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(lJudul)
                .addContainerGap(102, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnTampil)
                        .addGap(18, 18, 18)
                        .addComponent(btnSembunyi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInput)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lJudul)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampil)
                    .addComponent(btnSembunyi)
                    .addComponent(btnInput))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void tampilData(){
        try {
            DefaultTableModel tblModel = (DefaultTableModel)tblData.getModel();
            tblModel.setRowCount(0);
            
            String query = "SELECT * FROM datamhs";
            connector.statement = connector.koneksi.createStatement();
            ResultSet rs = connector.statement.executeQuery(query); 
            while(rs.next()){
                String nim = rs.getString("nim");
                String nama = rs.getString("nama");
                String fakultas = rs.getString("fakultas");
                String prodi = rs.getString("prodi");
                String email = rs.getString("email");
                String tahun = rs.getString("tahun_masuk");
                String status = rs.getString("status");
                
                String tbData[] = {nim,nama,fakultas,prodi,email,tahun,status};
                
                tblModel.addRow(tbData);
            }
        } catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void sembunyiData(){
        try {
            DefaultTableModel tblModel = (DefaultTableModel)tblData.getModel();
            tblModel.setRowCount(0);
        } catch (Exception ex){
            System.out.println(ex.getMessage());
        }
    }
    
    public void inputData(){
        viewInput.setVisible(true);
        viewInput.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void updateData(){
        int index = tblData.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)tblData.getModel();
        
        String nim = model.getValueAt(index, 0).toString();
        String nama = model.getValueAt(index, 1).toString();
        String fakultas = model.getValueAt(index, 2).toString();
        String prodi = model.getValueAt(index, 3).toString();
        String email = model.getValueAt(index, 4).toString();
        String tahun = model.getValueAt(index, 5).toString();
        String status = model.getValueAt(index, 6).toString();
        
        viewUpdate.setVisible(true);
        viewUpdate.pack();
        viewUpdate.setLocationRelativeTo(null);
        viewUpdate.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        viewUpdate.lNim.setText(nim); viewUpdate.lNim.setVisible(false);
        viewUpdate.tfNim.setText(nim);
        viewUpdate.lNama.setText(nama); viewUpdate.lNama.setVisible(false);
        viewUpdate.tfNama.setText(nama);
        viewUpdate.lFakultas.setText(fakultas); viewUpdate.lFakultas.setVisible(false);
        viewUpdate.tfFakultas.setText(fakultas);
        viewUpdate.lProdi.setText(prodi); viewUpdate.lProdi.setVisible(false);
        viewUpdate.tfProdi.setText(prodi);
        viewUpdate.lEmail.setText(email); viewUpdate.lEmail.setVisible(false);
        viewUpdate.tfEmail.setText(email);
        viewUpdate.lTahun.setText(tahun); viewUpdate.lTahun.setVisible(false);
        viewUpdate.tfTahun.setText(tahun);
        viewUpdate.lStatus.setText(status); viewUpdate.lStatus.setVisible(false);
        viewUpdate.tfStatus.setText(status);
    } 
    
    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        // TODO add your handling code here:
        tampilData();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnSembunyiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSembunyiActionPerformed
        // TODO add your handling code here:
        sembunyiData();
    }//GEN-LAST:event_btnSembunyiActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        inputData();
    }//GEN-LAST:event_btnInputActionPerformed
    
    private void tblDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataMouseClicked
        // TODO add your handling code here:
        updateData();
    }//GEN-LAST:event_tblDataMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuTabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuTabel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnSembunyi;
    private javax.swing.JButton btnTampil;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lJudul;
    private javax.swing.JTable tblData;
    // End of variables declaration//GEN-END:variables
}
